### ISSUE TITLE
2.0这个版本生成的日志文件不能按日志级别保存

### ISSUE THREAD

**Issue by TerryLiu** [georgehao/log#1]
2.0这个版本生成的日志文件没有自动保存为xxx.log.DEBUG，xxx.log.INFO, xxx.log.WARN, xxx.log.ERROR
而是全部保存为了xxx.log

**Comment by georgehao** [comment]
这个经过我考虑, 我觉得这些DEBUG, INFO, WARN, ERROR打在一个文件里, 其实更适合日志去分析, 所以我就做了2个版本, 1.0是分开的, 2.0是合在一块的
